import { StyleSheet } from 'react-native';
import { COLORS } from '@/constants/medstack-colors';

export const sharedStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  centerBox: { alignItems: 'center', paddingTop: 60, gap: 8, paddingHorizontal: 10 },
  card: { backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.line, borderRadius: 14 },
  eyebrow: { fontSize: 11, fontWeight: '700', letterSpacing: 1, color: COLORS.inkFaint, textTransform: 'uppercase' },
  h2: { fontSize: 19, fontWeight: '400', color: COLORS.ink, textAlign: 'center', fontFamily: 'Georgia', paddingHorizontal: 10 },
  subtle: { fontSize: 13, color: COLORS.inkSoft, textAlign: 'center' },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  btnPrimary: {
    backgroundColor: COLORS.teal,
    borderRadius: 26,
    paddingVertical: 13,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    alignSelf: 'center',
  },
  btnPrimaryFull: {
    backgroundColor: COLORS.teal,
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnPrimaryText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  btnGhost: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  btnGhostText: { color: COLORS.ink, fontSize: 14, fontWeight: '500' },
  input: {
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 10,
    padding: 11,
    fontSize: 15,
    marginTop: 6,
    color: COLORS.ink,
    backgroundColor: COLORS.surface,
  },
  errorText: { color: COLORS.redInk, fontSize: 12.5, marginTop: 10 },
  chip: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 5, paddingHorizontal: 11, borderRadius: 20 },
  chipDot: { width: 7, height: 7, borderRadius: 4 },
  filterChip: { paddingVertical: 6, paddingHorizontal: 12, borderRadius: 20, borderWidth: 1, borderColor: COLORS.line, marginRight: 6 },
  filterChipActive: { backgroundColor: COLORS.teal, borderColor: COLORS.teal },
  filterChipText: { fontSize: 12, fontWeight: '500', color: COLORS.inkSoft },
  filterChipTextActive: { color: '#fff' },
  drugName: { fontSize: 15, fontWeight: '600', color: COLORS.ink, textTransform: 'capitalize' },
});
